export const Properties = [
  {
    image: "src/assets/dummy1.jpg",
    streetNumber: "12",
    streetName: "Bromma",
    city: "Stockholm",
    country: "Sweden",
    size: 80,
    roomNumber: 2,
    type: "Apartment",
    price: 10000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy2.jpeg",
    streetNumber: "25",
    streetName: "Södermalm",
    city: "Stockholm",
    country: "Sweden",
    size: 90,
    roomNumber: 4,
    type: "Condo",
    price: 11000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy3.jpeg",
    streetNumber: "45",
    streetName: "Kungsholmen",
    city: "Stockholm",
    country: "Sweden",
    size: 100,
    roomNumber: 3,
    type: "Townhouse",
    price: 12000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy4.jpeg",
    streetNumber: "67",
    streetName: "Östermalm",
    city: "Stockholm",
    country: "Sweden",
    size: 110,
    roomNumber: 7,
    type: "Villa",
    price: 13000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy5.jpeg",
    streetNumber: "89",
    streetName: "Vasastan",
    city: "Stockholm",
    country: "Sweden",
    size: 120,
    roomNumber: 4,
    type: "Loft",
    price: 14000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy6.jpeg",
    streetNumber: "101",
    streetName: "Djurgården",
    city: "Stockholm",
    country: "Sweden",
    size: 130,
    roomNumber: 3,
    type: "Bungalow",
    price: 15000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy7.jpeg",
    streetNumber: "123",
    streetName: "Norrmalm",
    city: "Stockholm",
    country: "Sweden",
    size: 140,
    roomNumber: 4,
    type: "Cottage",
    price: 16000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy8.jpeg",
    streetNumber: "145",
    streetName: "Gärdet",
    city: "Stockholm",
    country: "Sweden",
    size: 150,
    roomNumber: 4,
    type: "Mansion",
    price: 17000,
    currency: "SEK",
  },
  {
    image: "src/assets/dummy9.jpeg",
    streetNumber: "167",
    streetName: "Skärholmen",
    city: "Stockholm",
    country: "Sweden",
    size: 160,
    roomNumber: 5,
    type: "Duplex",
    price: 18000,
    currency: "SEK",
  },
  // Add more properties here...
];

export const Tenants = [
  {
    image: "src/assets/person1.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 10000,
    currency: "SEK",
  },
  {
    image: "src/assets/person2.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 11000,
    currency: "SEK",
  },
  {
    image: "src/assets/person3.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 12000,
    currency: "SEK",
  },
  {
    image: "src/assets/person4.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 13000,
    currency: "SEK",
  },
  {
    image: "src/assets/person5.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 14000,
    currency: "SEK",
  },
  {
    image: "src/assets/person6.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 15000,
    currency: "SEK",
  },
  {
    image: "src/assets/person7.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 16000,
    currency: "SEK",
  },
  {
    image: "src/assets/person8.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 17000,
    currency: "SEK",
  },
  {
    image: "src/assets/person9.jpeg",
    city: "Stockholm",
    country: "Sweden",
    price: 18000,
    currency: "SEK",
  },
  // Add more properties here...
];
